### ISSUE TITLE
Remove unnecessary first br/block on functions with more complex control flow

### ISSUE THREAD

**Issue by edg-l** [lambdaclass/cairo_sierra_2_MLIR#50]
As the title says, methods with jumps and branching add a block that acts like the entry block, we should just use the entry block.

**Comment by DomHenderson** [comment]
The entry block acts as an argument filter, since dataflow only adds block arguments for data that is used, but functions can have parameters that are not (especially since we currently ignore functions like drop, and could well ignore several more in the future). Additionally it avoids any potential issues with mlir's restrictions on jumping to entry blocks
